window.questionObj = null;

var questionObj = {
	title: "高级前端面试题",
	questionList: [
		{
			isMul: "multiple",
			type: "textarea",
			topic: "请简述px,em,rem的原理以及异同点",
			keywords: 'em,rem',
			answer: "DIY",
			point: 8,
		},
		{
			isMul: "multiple",
			type: "textarea",
			topic: "前端路由跳转的原理",
			keywords: 'hash,history',
			answer: "DIY",
			point: 8,
		},
		{
			isMul: "multiple",
			type: "textarea",
			topic: "详细描述http的缓存机制",
			keywords: 'http cache',
			answer: "DIY",
			point: 8,
		},
		{
			isMul: "multiple",
			type: "textarea",
			topic: "http2相比之前有哪些进步? https呢?",
			keywords: 'http2,https',
			answer: "DIY",
			point: 10,
		},
		{
			isMul: "multiple",
			type: "textarea",
			topic: "web性能优化有哪些, 越多越好, 不少于8项",
			answer: "DIY",
			keywords: 'web性能优化',
			point: 8,
		},
		{
			isMul: "multiple",
			type: "textarea",
			topic: "js的异步方案有哪些",
			answer: "DIY",
			keywords: '异步js',
			point: 8,
		},
		{
			isMul: "multiple",
			type: "textarea",
			topic: "如何及时有效的捕获前端出现的异常",
			answer: "DIY",
			keywords: '异步js',
			point: 8,
		},
		{
			isMul: "multiple",
			type: "textarea",
			topic: "请详细描述浏览器里Event Loop的运行机制",
			keywords: 'event loop',
			answer: "DIY",
			point: 10,
		},
		{
			isMul: "multiple",
			type: "textarea",
			topic: "xss和cros的原理以及预防",
			keywords: 'xss,cros',
			answer: "DIY",
			point: 10,
		},
		{
			isMul: "multiple",
			type: "textarea",
			topic: "webpack的loader和plugin的运行机制, 有写过吗?",
			keywords: 'loader,plugin',
			answer: "DIY",
			point: 10,
		},
		{
			isMul: "multiple",
			type: "textarea",
			topic: "请写一下防抖/节流函数, 并验证其正确性",
			keywords: 'throttle,debounce',
			answer: "DIY",
			point: 10,
		},
		{
			isMul: "multiple",
			type: "textarea",
			topic: "请描述一下Virtual DOM",
			keywords: 'virtual dom',
			answer: "DIY",
			point: 10,
		},
		{
			isMul: "multiple",
			type: "textarea",
			topic: "请描述一下Diff算法",
			keywords: 'diff',
			answer: "DIY",
			point: 10,
		},
		{
			isMul: "multiple",
			type: "textarea",
			topic: "Vue和React的异同点",
			keywords: 'vue,react',
			answer: "DIY",
			point: 10,
		},
		{
			isMul: "multiple",
			type: "textarea",
			topic: "试着描述一下react native, flutter, weex等的异同",
			keywords: 'react native, flutter, weex',
			answer: "DIY",
			point: 10,
		},
		{
			isMul: "multiple",
			type: "textarea",
			topic: "请说说你的职业规划",
			keywords: '职业规划',
			answer: "DIY",
			point: 10,
		},
	]
}

window.questionObj = questionObj;
